apiVersion: apps/v1
kind: Deployment
metadata:
  name: jokesapiv2-2-25-23
  labels:
    app: jokesapiv2-2-25-23
  namespace: jokesapiv2-2-25-23
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jokesapiv2-2-25-23
  template:
    metadata:
      labels:
        app: jokesapiv2-2-25-23
    spec:
      containers:
        - name: jokesapiv2-2-25-23
          image: crazk8sehiebdpdv2i7fmty6.azurecr.io/jokesapiv2-2-25-23:latest
          ports:
            - containerPort: 3000