apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: jokesapi
  name: jokesapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jokesapi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jokesapi
    spec:
      containers:
      - image: craks1210ayyagi3sofrye.azurecr.io/jokesapi
        name: jokesapi
        ports:
        - containerPort: 3000
        resources: {}
status: {}
