apiVersion: apps/v1
kind: Deployment
metadata:
  name: jokesapiv2-5-10-23-run1
  labels:
    app: jokesapiv2-5-10-23-run1
  namespace: jokesapiv2-5-10-23-run1-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jokesapiv2-5-10-23-run1
  template:
    metadata:
      labels:
        app: jokesapiv2-5-10-23-run1
    spec:
      containers:
        - name: jokesapiv2-5-10-23-run1
          image: crcrplaneazk8s4i7zlvwos5tsldzdw.azurecr.io/jokesapiv2-5-10-23-run1-img:latest
          ports:
            - containerPort: 3000