apiVersion: v1
kind: Service
metadata:
  name: jsapitestworkflow2
  namespace: jsapitestworkflow2-ns
spec:
  type: LoadBalancer
  selector:
    app: jsapitestworkflow2
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000