apiVersion: v1
kind: Service
metadata:
  name: jokesapiv2-2-25-23
  namespace: jokesapiv2-2-25-23
spec:
  type: LoadBalancer
  selector:
    app: jokesapiv2-2-25-23
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000