apiVersion: v1
kind: Service
metadata:
  name: jokesapiv2-42623-run0
  namespace: jokesapiv2-42623-run0
spec:
  type: LoadBalancer
  selector:
    app: jokesapiv2-42623-run0
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000