apiVersion: v1
kind: Service
metadata:
  name: jokesapiv2-5-10-23-run1
  namespace: jokesapiv2-5-10-23-run1-ns
spec:
  type: LoadBalancer
  selector:
    app: jokesapiv2-5-10-23-run1
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000