apiVersion: v1
kind: Service
metadata:
  name: azurefridayadforaksdemo
  namespace: azurefridayadforaksdemo-ns
spec:
  type: LoadBalancer
  selector:
    app: azurefridayadforaksdemo
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000