apiVersion: v1
kind: Service
metadata:
  name: JS-test-workflow1
  namespace: js-test-workflow1-1-ns
spec:
  type: LoadBalancer
  selector:
    app: JS-test-workflow1
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000